parameters:
    pengarwin.organization_handler.class: PengarWin\DoubleEntryBundle\Model\OrganizationHandler
    pengarwin.account_handler.class:      PengarWin\DoubleEntryBundle\Model\AccountHandler
    pengarwin.account_selector.class:     PengarWin\DoubleEntryBundle\Form\Type\AccountSelectorType
    pengarwin.vendor_handler.class :      PengarWin\DoubleEntryBundle\Model\VendorHandler
    pengarwin.vendor_selector.class:      PengarWin\DoubleEntryBundle\Form\Type\VendorSelectorType

    pengarwin.account_param_converter.class: PengarWin\DoubleEntryBundle\Request\ParamConverter\AccountParamConverter

services:
    pengarwin.organization_handler:
        class: %pengarwin.organization_handler.class%
        arguments:
            - %pengarwin.organization.class%
            - @security.context
            - @doctrine.orm.entity_manager

    pengarwin.vendor_handler:
        class: %pengarwin.vendor_handler.class%
        arguments:
            - %pengarwin.vendor.class%
            - @pengarwin.organization_handler
            - @doctrine.orm.entity_manager

    pengarwin.account_handler:
        class: %pengarwin.account_handler.class%
        arguments:
            - %pengarwin.account.class%
            - @pengarwin.organization_handler
            - @doctrine.orm.entity_manager

    pengarwin.type.vendor_selector:
        class: %pengarwin.vendor_selector.class%
        arguments:
            - @pengarwin.vendor_handler
        tags:
            - { name: form.type, alias: vendor_selector }

    pengarwin.type.account_selector:
        class: %pengarwin.account_selector.class%
        arguments:
            - @pengarwin.account_handler
        tags:
            - { name: form.type, alias: account_selector }

    pengarwin.account_param_converter:
        class:     %pengarwin.account_param_converter.class%
        arguments:
            - @pengarwin.account_handler
        tags:
            - { name: request.param_converter, converter: account, priority: 10 }
