parameters:
    phospr.organization_handler.class: Phospr\DoubleEntryBundle\Model\OrganizationHandler
    phospr.account_handler.class:      Phospr\DoubleEntryBundle\Model\AccountHandler
    phospr.account_selector.class:     Phospr\DoubleEntryBundle\Form\Type\AccountSelectorType
    phospr.vendor_handler.class :      Phospr\DoubleEntryBundle\Model\VendorHandler
    phospr.vendor_selector.class:      Phospr\DoubleEntryBundle\Form\Type\VendorSelectorType

    phospr.journal_handler.class :     Phospr\DoubleEntryBundle\Model\JournalHandler
    phospr.posting_handler.class :     Phospr\DoubleEntryBundle\Model\PostingHandler

    phospr.account_param_converter.class: Phospr\DoubleEntryBundle\Request\ParamConverter\AccountParamConverter
    phospr.journal_param_converter.class: Phospr\DoubleEntryBundle\Request\ParamConverter\JournalParamConverter

    phospr.form.type.journal.class:    Phospr\DoubleEntryBundle\Form\Type\JournalType
    phospr.form.type.posting.class:    Phospr\DoubleEntryBundle\Form\Type\PostingType

services:
    phospr.organization_handler:
        class: %phospr.organization_handler.class%
        arguments:
            - %phospr.organization.class%
            - @security.context
            - @doctrine.orm.entity_manager

    phospr.vendor_handler:
        class: %phospr.vendor_handler.class%
        arguments:
            - %phospr.vendor.class%
            - @phospr.organization_handler
            - @doctrine.orm.entity_manager

    phospr.account_handler:
        class: %phospr.account_handler.class%
        arguments:
            - %phospr.account.class%
            - @phospr.organization_handler
            - @doctrine.orm.entity_manager

    phospr.journal_handler:
        class: %phospr.journal_handler.class%
        arguments:
            - %phospr.journal.class%
            - @phospr.organization_handler
            - @doctrine.orm.entity_manager

    phospr.posting_handler:
        class: %phospr.posting_handler.class%
        arguments:
            - %phospr.posting.class%
            - @phospr.organization_handler
            - @doctrine.orm.entity_manager

    phospr.type.vendor_selector:
        class: %phospr.vendor_selector.class%
        arguments:
            - @phospr.vendor_handler
        tags:
            - { name: form.type, alias: vendor_selector }

    phospr.type.account_selector:
        class: %phospr.account_selector.class%
        arguments:
            - @phospr.account_handler
        tags:
            - { name: form.type, alias: account_selector }

    phospr.account_param_converter:
        class:     %phospr.account_param_converter.class%
        arguments:
            - @phospr.account_handler
        tags:
            - { name: request.param_converter, converter: account, priority: 10 }

    phospr.journal_param_converter:
        class:     %phospr.journal_param_converter.class%
        arguments:
            - @phospr.journal_handler
        tags:
            - { name: request.param_converter, converter: journal, priority: 10 }


    phospr.form.type.journal:
        class: %phospr.form.type.journal.class%
        arguments:
            - @phospr.journal_handler
        tags:
            - { name: form.type, alias: journal }

    phospr.form.type.posting:
        class: %phospr.form.type.posting.class%
        arguments:
            - @phospr.posting_handler
        tags:
            - { name: form.type, alias: posting }
